### boot配置文件 ###
spring:
  profiles:
    # 选择配置文件
    active: dev
  application:
    name: manager
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB


server:
  port: 8080
  max-http-header-size: 10240
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /manager-web

#mybatis
#mybatis:
#  type-aliases-package: com.beadwallet.main.model.entity
#  mapper-locations: classpath:mapping/*.xml
#  configuration:
#    # 缓存
#    cache-enabled: false
#    # 打印sql日志
##    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    #下划线大小替换
#    mapUnderscoreToCamelCase: true
#mappers
mapper:
  mappers: com.manager.common.data.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#debug: true

# shiro
#shiro:
#  captcha:
#    enable: true
#    # 验证码类型 math/char
#    type: math
