### boot配置文件 ###
spring:
  profiles:
    # 选择配置文件
    active: dev
  application:
    name: job
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false


server:
  port: 8180
  max-http-header-size: 10240
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /job

mapper:
  mappers: com.vd.common.data.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#debug: true
